"""empty message

Revision ID: f047d58de9bd
Revises: 04b0eed30d4c
Create Date: 2020-01-28 08:58:49.648963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f047d58de9bd'
down_revision = '04b0eed30d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pass_secure', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pass_secure')
    # ### end Alembic commands ###
